* Number Sense
1. Practice seeing relationships
   How does 5 relate to 10? 3 to 9?
2. See only the answer
   Read 4 + 3 as 7—not as four plus three.
3. Work from left to right
   27 is 27—not 7, 2.
4. Convert to simpler forms
   25¢ is both 25¢ and a quarter of a dollar.
   99 is 100 minus 1.
   15 is 10 plus ½ of 10.
* Adding (Walking right on the number line)
+ When adding two numbers <10 that go over 10, take the complement of the larger digit and subtract it with the smaller digit and add/record a 10.
  9 + 4 = (10-1) + 4 = 10 + (4-1) = 13 OR (9+1) + (4-1) = 13
+ For negative numbers [My own thoughts] :-
  + When adding two negative numbers, strip the negative off both and add the two digits and then put back the negative.
  + When adding a negative number with a positive one, subtract the higher digit from the smaller one and add a negative sign back if it does not go over 0.
** Automatic Estimating
Since we are going left to right we can just stop and ignore all numbers to the right
** Rules to speed up adding
If adding multiple digits, group the pair of digits that don't go over 10.
3 + 4 + 2 + 6 + 3 + 7 + 5 + 3
( 7 ) + ( 8 ) + ( 10 ) + ( 8 )
* Subtracting (Walking left on the number line)
+ When subtracting two numbers <10 that go under 0, take the complement of the larger digit and add it with the smaller digit and subtract/cancel a 10.
  43 - 8 = 43 - (10-2) = (43-10) + 2 = 35 OR (43+2) - (8+2) = 45 - 10 = 35
+ If you are cancelling a 0, the zero becomes a 9 and you need to cancel another 10.
  158 - 59 = 10(9 cancel a 10) = 1(9 cancel a 10 again)9 = 099
+ For negative numbers [My own thoughts] :-
  + When subtracting two negative numbers, remember that going left on the number line of a negative number is really going right on the number line so eventually you will end up with a negative number number add a positive one.
  + When subtracting a negative number with a positive one, add the two numbers and put back the negative sign.
** Automatic Estimating
Since we are going left to right we can just stop and ignore all numbers to the right
* Multiplication (Running right on the number line)
Honestly a lot easier to jump straight into examples
** Full example with 2 digit numbers - 26 x 98
  1. Get the product of the first two numbers going left to right in two digits (adding 0's if product < 10)
     a) 2 * 9 = 18, Write the 1 down and save the 8
     ANSWER:
     1
  2. Get the product of the next two numbers
     a) 6 * 9 = 54
     b) Add the first digit with the saved second digit of the previous product => 8 + 5 = 3 carry 1, Write 3 and increment previous digit
     c) There are no more numbers left in the first line so we can write the second digit 4
     ANSWER:
     234
  3. Get the product of the next two numbers
     a) For every new line, you start one place to the right of the previous
     b) 2 * 8 = 16, Write the 1 down and save the 6
     ANSWER:
     234
      1
  4. Get the product of the next two numbers
     a) 6 * 8 = 48
     b) Add the first digit with the saved second digit of the previous product => 6 + 4 = 0 carry 1, Write 0 and increment previous digit
     c) There are no more numbers left in the first line so we can write the second digit 8
     ANSWER:
     234
      208
  5. Add the two numbers together filling the blanks with 0's = 2340 + 208 = 2548
** Example with a lot of 0's - 170 * 30
  Line 1:
  a) 1 * 3 = 03 = 0 save 3
  b) 7 * 3 = 21 => 3 + 2 = 5 => 05 save 1
  c) 0 * 3 = 00 => 1 + 0 = 0 => 0510
  Line 2:
  a) 1 * 0 = 00 = 0 save 0
  b) 7 * 0 = 00 => 0 + 0 = 0 => 00 save 0
  c) 0 * 0 = 00 => 0 + 0 = 0 => 0000
  SUM:
   0510
  + 0000
  ________
   05100
** 3 digit example - 976 * 438
  Line 1:
  a) 9 * 4 = 3, save 6
  b) 7 * 4 = 28 => 6 + 2 = 8 = 38, save 8
  c) 6 * 4 = 24 => 8 + 2 = 0 carry 1 = 3904
  Line 2:
  a) 9 * 3 = 27 = 2, save 7
  b) 7 * 3 = 21 => 7 + 2 = 9 = 29, save 1
  c) 6 * 3 = 18 => 1 + 1 = 2 = 2928
  Line 3:
  a) 9 * 8 = 72 = 7, save 2
  b) 7 * 8 = 56 => 2 + 5 = 77, save 6
  c) 6 * 8 = 48 => 6 + 4 = 0 carry 1 = 7808
  SUM:
    3904
  _+_  2928
      7808
    ________
    316488
    111
    ________
    427488
** Automatic Estimating
To estimate in multiplication, go as far as you have to and stop. Then raise the last digit by one for each two digits in the multiplier.
*** For example you to buy 53,926 items at $48.75 each, estimating to 3 digits
1.
   Line 1:
   a) 5 * 4 = 20 = 2, save 0
   b) 3 * 4 = 12 => 1 + 0 = 1 = 21, save 2
   c) 9 * 4 = 36 => 2 + 3 = 5 = 215, drop the 6
   Line 2:
   a) 5 * 8 = 40 = 4, save 0
   b) 3 * 8 = 24 => 2 + 0 = 42, drop the 4
   Line 3:
   a) 5 * 7 = 35 = 3, drop the 5
   SUM:
    215
   _+_ 42
      3
    _____
    260
2. Now because there are four digits in the multiplier, you increment the last digit of the sum twice => 260 becomes 262
3. The final answer has exactly as many digits as the total of the two numbers multiplied NOT including the digits after the decimal
   A few disclaimers on this:
   + Numbers after a decimal point are not counted
   + If the first digit in the first line step of the answer is 0 (like 2 * 2 = 02), then you need to decrement the total digit value by 1
4. So 53,926 has 5 digits, and 48.75 has two digits => final answer must have 7 digits total so we end up with 2,620,000 with the real answer being 2,628,892.50
*** An example for decrementing the total digits - 2468 x 28, estimating to 2 digits
1.
   Line 1:
   a) 2 * 2 = 04 = 0, save the 4
   b) 4 * 2 = 08 => 0 + 4 = 4 = 04, drop the 8
   Line 2:
   a) 4 * 2 = 08 = 0, drop the 8
   SUM:
    04
   _+_ 0
    __
    04
2. 2 digits in the multiplier => 04 = 06
3. Total number of digits of the two numbers multiplied = 4 + 2 = 6 BUT we had a 0 in the first answer so we drop it by 1 = 5
4. Final estimate answer = 60,000, with real answer being 68,900
* Division (Running left on the number line)
** An example for multi-digit division with first digit of divisor > first digit of divident  - 423 / 236048
1.
   a) First digit of divisor is 4, 4 + 1 = 5
   b) 5 is greater than 2 (first digit of divident) so we look at the first two digits instead. 5 goes into 23 4 times (5 * 4 = 20)
   c) divisor is 3 digits long so we place 4 over divident by the number of divisor digits + 1 (since we looked at first two digits) => 4 over the 0
2. Line 1:
   a) 4 into 4, first digit is 1, and 2 - 1 = 1
                4
      423)   236048
           - 1
           _______
             1
   b)
      i) 4 into 4 last digit is 6
      ii) 2 into 4 first digit = 0
      iii) 6 + 0 = 6
      iv) 3 - 6 = 7 cancel one from left
                4
      423)   236048
           - 16
           _______
             07
   c)
      i) 2 into 4 last digit is 8
      ii) 3 into 4 first digit = 1
      iii) 8 + 1 = 9
      iv) 6 - 9 = 7, cancel one from left
                4
      423)   236048
           - 169
           _______
             067
   d)
     i) 3 into 4 last digit = 2
     ii) 0 - 2 = 8, cancel one from left
                4
      423)   236048
           - 1692
           __________
             0668

3. 668 > 423 so we need to revise initial answer of 4. We subtract our new divident (668) by divisor until it's less than divisor. For each subtraction you add 1 to your answer. 668 - 423 = 245 so answer is 4 + 1 = 5 and new divident (245) < 423. Now we drop the 4 from original divident and new divident is 2454.
4.
   a) First digit of divisor is 4, 4 + 1 = 5
   b) 5 is greater than 2 (first digit of divident) so we look at the first two digits instead. 5 goes into 24 4 times
   c) Place 4 after 5
5. Line 2:
   a) 4 into 4, first digit is 1, and 2 - 1 = 1
                54
      423)   236048
           - 1692
           __________
             0668
           - 0423
           __________
              2454
           -  1
           __________
              1
   b)
      i) 4 into 4 last digit is 6
      ii) 2 into 4 first digit = 0
      iii) 6 + 0 = 6
      iv) 4 - 6 = 8 cancel one from left
                54
      423)   236048
           - 1692
           __________
             0668
           - 0423
           __________
              2454
           -  16
           __________
              08
   c)
      i) 2 into 4 last digit is 8
      ii) 3 into 4 first digit = 1
      iii) 8 + 1 = 9
      iv) 5 - 9 = 6, cancel one from left
                54
      423)   236048
           - 1692
           __________
             0668
           - 0423
           __________
              2454
           -  169
           __________
              076
   d)
     i) 3 into 4 last digit = 2
     ii) 4 - 2 = 2
                54
      423)   236048
           - 1692
           __________
             0668
           - 0423
           __________
              2454
           -  1692
           __________
              0762
6. 762 > 423 so we need to revise initial answer of 4. We subtract our new divident (762) by divisor until it's less than divisor. For each subtraction you add 1 to your answer. 762 - 423 = 339 so answer is 4 + 1 = 5 and new divident (339) < 423. Now we drop the 8 from original divident and new divident is 3398.
7.
   a) First digit of divisor is 4, 4 + 1 = 5
   b) 5 is greater than 3 (first digit of divident) so we look at the first two digits instead. 5 goes into 33 6 times (5 * 6 = 30)
   c) Place 6 after 5
8. Line 3:
   a) 4 into 6, first digit is 2, and 3 - 2 = 1
                556
      423)   236048
           - 1692
           __________
             0668
           - 0423
           __________
              2454
           -  1692
           __________
              0762
           -  0423
           __________
               3398
           -   2
           __________
               1
   b)
      i) 4 into 6 last digit is 4
      ii) 2 into 6 first digit = 1
      iii) 4 + 1 = 5
      iv) 3 - 5 = 8 cancel one from left
                556
      423)   236048
           - 1692
           __________
             0668
           - 0423
           __________
              2454
           -  1692
           __________
              0762
           -  0423
           __________
               3398
           -   25
           __________
               08
   c)
      i) 2 into 6 last digit is 2
      ii) 3 into 6 first digit = 1
      iii) 2 + 1 = 3
      iv) 9 - 3 = 6
                556
      423)   236048
           - 1692
           __________
             0668
           - 0423
           __________
              2454
           -  1692
           __________
              0762
           -  0423
           __________
               3398
           -   253
           __________
               086
   d)
     i) 3 into 6 last digit = 8
     ii) 8 - 8 = 0
                556
      423)   236048
           - 1692
           __________
             0668
           - 0423
           __________
              2454
           -  1692
           __________
              0762
           -  0423
           __________
               3398
           -   2538
           __________
               0860
9. 860 > 423 so we need to revise initial answer of 4. We subtract our new divident (860) by divisor until it's less than divisor. For each subtraction you add 1 to your answer. 860 - 423 = 437 so answer is 4 + 1 = 5 and new divident (437) > 423. 437 - 423 = 14. There is no more numbers to drop so we have reached the end of the answer.
10. ANSWER: 558 Remainder 14
** An example for multi-digit division with first digit of divisor < first digit of divident  - 27 / 823
1.
   a) First digit of divisor is 2, 2 + 1 = 3
   b) 3 is less than 8 (first digit of divident). 3 goes into 8 2 times (3 * 2 = 6)
   c) divisor is 2 digits long so we place 2 over divident by the number of divisor digits => 2 over the 2
2. Line 1:
   a) Since we only divided into only the first digit of the divident, not the first two like the previous example, we skip the first digit of this step. We do not do 2 * 2 first digit = 0, 8 - 0 = 8....
   b)
      i) 2 into 2 last digit is 4
      ii) 7 into 2 first digit = 1
      iii) 4 + 1 = 5
      iv) 8 - 5 = 3
             2
      27)    823
           - 5
           _______
             3
   c)
     i) 7 into 2 last digit = 4
     ii) 2 - 4 = 8, cancel one from left
             2
      27)    823
           - 54
           _______
             28

3. 28 > 27 so we need to revise initial answer of 3. 28 - 27 = 01 so answer is 2 + 1 = 3 and new divident (01) < 27. Now we drop the 3 from original divident and new divident is 013.
4. 27 goes into 13 0 times
             30
      27)    823
           - 54
           _______
             28
           - 27
           _______
             013
           -   0
           _______
              13

10. ANSWER: 30 Remainder 13
** Building Speed in Division
You can round of the divisor first and then the divident by the same number of digits.
+ 68,392) 268,595,471
  - 68392 can be rounded to 3 digits to 684
  - Because we dropped 2 digits from the divisor we remove 2 digits from the divident = 2,685,955
